<?php
/**
 * @category  SixtySeven
 * @package   SixtySeven_ProductVideo
 * @author    67Digital http://67digital.com/
 */

/**
 * Product media data template
 *
 * @var $block \SixtySeven\ProductVideo\Block\Product\View\Gallery
 */
?>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "SixtySeven_UploadVideo/js/fotorama-add-video-events": {
                "videoData": <?= /* @escapeNotVerified */ $block->getMediaGalleryDataJson() ?>,
                "videoSettings": <?= /* @escapeNotVerified */ $block->getVideoSettingsJson() ?>,
                "optionsVideoData": <?= /* @noEscape */ $block->getOptionsMediaGalleryDataJson() ?>
            }
        }
    }
</script>
 